# Generated by Django 2.1.3 on 2018-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('DFT', 'Draft')], default='PUB', max_length=3),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
