# Generated by Django 2.1.3 on 2018-11-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
