# Generated by Django 2.1.3 on 2018-11-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20181120_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='blog'),
            preserve_default=False,
        ),
    ]
